import type { DecisionItem } from "./types";

/**
 * Seed decisions for the Decision Centre and Workflow Centre. Deterministic
 * demo work items spanning all four stakeholder command centres and every
 * lifecycle stage, so the workflow board reads as a living pipeline. Evidence
 * lineage references the real lakehouse zones; marts not yet built are marked
 * planned/demo, matching the platform's provenance-honesty rule.
 */

const ASOF = "as of 07 Jul 2026, 14:20 UTC";

/** Bump when the seed shape changes — invalidates persisted overlays. */
export const SEED_VERSION = "2026-07-11.1";

export const SEED_DECISIONS: DecisionItem[] = [
  {
    id: "dec-reefer-leakage",
    sev: "hi",
    stakeholder: "Port Authority",
    problem: "Revenue leakage up 7% on reefer tariffs",
    body: "Reefer plug-in fees under-billed vs manifest on 214 calls this quarter — the largest correctable loss on the tariff book.",
    valueAtRisk: { label: "Revenue at stake", amount: "$1.9M" },
    confidence: 0.68,
    recommendation: "Reconcile the reefer tariff rule and back-bill the 214 affected calls this quarter.",
    expectedOutcome: "Recover ≈$1.9M this quarter and close the rule gap so leakage stops accruing.",
    owner: "N. Dlamini · Revenue Manager",
    dueDate: "2026-07-18",
    stage: "recommendation",
    state: "open",
    relatedObjects: [
      { label: "port:durban", href: "/ontology/port/durban" },
      { label: "tariff:reefer" },
      { label: "SDG 8" },
    ],
    watchers: ["Port CFO", "Commercial Director"],
    tasks: [],
    evidence: {
      metric: "Reefer revenue leakage",
      value: "$1.9M",
      objectRef: "object · tariff:reefer @ port:durban",
      asOf: "quarter to 07 Jul 2026",
      confidence: 0.68,
      status: "demo",
      lineage: [
        { zone: "bronze", title: "Manifests + tariff records", locator: "pillar/finance · CRM*", detail: "Billed fees vs manifested reefer plug-ins. First-party CRM source is a deferred data product.", sources: ["finance", "crm* (planned)"] },
        { zone: "silver", title: "Reconcile billed vs due", locator: "tariff_reconciliation*", detail: "Matched 214 calls; flagged under-billed lines.", sources: ["rule-based"] },
        { zone: "gold", title: "Revenue leakage", locator: "gold_revenue_leakage*", detail: "Sum of under-billed reefer tariff lines. Illustrative — mart not yet built.", sources: ["estimate", "planned"] },
      ],
      recommendation: "Reconcile the reefer tariff rule and back-bill; est. recovery $1.9M this quarter.",
    },
    activity: [
      { at: "2026-07-07T06:40:00Z", actor: "Sinapse", kind: "created", text: "Raised by the recommendation engine — billed vs manifested reefer fees diverged past the 5% threshold." },
    ],
    version: 1,
  },
  {
    id: "dec-msc-renewal",
    sev: "md",
    stakeholder: "Port Authority",
    problem: "MSC contract renewal in 12 days",
    body: "MSC is 22% of container volume. Health score dipped as Durban's congestion rose above peer ports.",
    valueAtRisk: { label: "Annual volume", amount: "0.62M TEU" },
    confidence: 0.55,
    recommendation: "Open renewal with a berth-window guarantee; model a 3% rate concession vs churn risk.",
    expectedOutcome: "Retain the 0.62M TEU/yr account with margin loss capped at 3%.",
    owner: "T. Naidoo · Commercial Director",
    dueDate: "2026-07-19",
    stage: "recommendation",
    state: "open",
    relatedObjects: [
      { label: "customer:MSC" },
      { label: "port:durban", href: "/ontology/port/durban" },
      { label: "corridor:durban-lusaka", href: "/ontology/corridor/durban-lusaka" },
    ],
    watchers: ["Port CEO"],
    tasks: [],
    evidence: {
      metric: "MSC customer health",
      value: "62",
      objectRef: "object · customer:MSC",
      asOf: ASOF,
      confidence: 0.55,
      status: "planned",
      lineage: [
        { zone: "bronze", title: "CRM + volume history", locator: "CRM* · pillar/ais", detail: "First-party account data is deferred; volume proxied from AIS calls.", sources: ["crm* (planned)", "ais proxy"] },
        { zone: "silver", title: "Enrich & score signals", locator: "customer_health*", detail: "Volume trend, congestion exposure, contract stage.", sources: ["partial data"] },
        { zone: "gold", title: "Customer Health Score", locator: "gold_customer_health*", detail: "Composite churn-risk index. Low confidence until CRM lands.", sources: ["planned"] },
      ],
      recommendation: "Open renewal with a berth-window guarantee; model a 3% concession vs churn risk.",
    },
    activity: [
      { at: "2026-07-06T09:15:00Z", actor: "Sinapse", kind: "created", text: "Contract-stage trigger: renewal window opened with customer health below 65." },
    ],
    version: 1,
  },
  {
    id: "dec-nsc-growth",
    sev: "gd",
    stakeholder: "Port Authority",
    problem: "North-South corridor growing +18% YoY",
    body: "Throughput on the Durban gateway is up 18% YoY — capacity headroom exists to capture the overflow.",
    valueAtRisk: { label: "Growth capture", amount: "+34k TEU" },
    confidence: 0.79,
    recommendation: "Prioritise North-South corridor slot allocation; flag to commercial for targeted outreach.",
    expectedOutcome: "Capture ≈34k TEU of incremental corridor volume over the next two quarters.",
    owner: "T. Naidoo · Commercial Director",
    dueDate: "2026-07-31",
    stage: "insight",
    state: "open",
    relatedObjects: [
      { label: "corridor:durban-lusaka", href: "/ontology/corridor/durban-lusaka" },
      { label: "port:durban", href: "/ontology/port/durban" },
      { label: "SDG 9" },
    ],
    watchers: [],
    tasks: [],
    evidence: {
      metric: "Corridor gateway throughput",
      value: "+18% YoY",
      objectRef: "object · corridor:durban-lusaka",
      asOf: "YoY to 07 Jul 2026",
      confidence: 0.79,
      status: "demo",
      lineage: [
        { zone: "bronze", title: "PortWatch gateway activity", locator: "pillar/port_activity", detail: "Origin-port daily calls & tonnage for the corridor gateway.", sources: ["portwatch"] },
        { zone: "silver", title: "Attribute to corridor", locator: "port_activity_daily", detail: "Joined via ont_corridor.origin_port_id (ontology link).", sources: ["ontology link"] },
        { zone: "gold", title: "Corridor gateway activity", locator: "gold_corridor_gateway_activity", detail: "30-day throughput at the coastal gateway port.", sources: ["gateway proxy"] },
      ],
      recommendation: "Prioritise North-South slot allocation; flag to commercial for targeted outreach.",
    },
    activity: [
      { at: "2026-07-05T11:00:00Z", actor: "Sinapse", kind: "created", text: "Growth anomaly: gateway throughput exceeded the 12-month trend band for a third consecutive month." },
    ],
    version: 1,
  },
  {
    id: "dec-swell-window",
    sev: "hi",
    stakeholder: "Port Authority",
    problem: "Thursday swell event threatens 6 berth windows",
    body: "Forecast 3.4m swell with 30kn gusts across Thursday's high tide — six scheduled Panamax windows sit inside the disruption band.",
    valueAtRisk: { label: "Demurrage exposure", amount: "$420k" },
    confidence: 0.82,
    recommendation: "Re-sequence two Panamax calls off the Thursday peak and pre-notify lines of a 12-hour slide.",
    expectedOutcome: "Hold anchorage wait under 18h through the weather window; avoid ≈$420k demurrage claims.",
    owner: "S. Mokoena · Harbour Master",
    dueDate: "2026-07-14",
    stage: "approval",
    state: "accepted",
    relatedObjects: [
      { label: "port:durban", href: "/ontology/port/durban" },
      { label: "weather:agulhas-swell" },
    ],
    watchers: ["Port Ops Room"],
    tasks: [],
    evidence: {
      metric: "Berth-window disruption risk",
      value: "High · 6 windows",
      objectRef: "object · port:durban",
      asOf: ASOF,
      confidence: 0.82,
      status: "demo",
      lineage: [
        { zone: "bronze", title: "Open-Meteo marine forecast", locator: "pillar/weather", detail: "Hourly wave height, period and wind for the port anchorage.", sources: ["open-meteo"] },
        { zone: "silver", title: "Disruption banding", locator: "marine_conditions", detail: "Wave/wind thresholds → low/moderate/high/severe risk bands, ontology-keyed.", sources: ["ontology-keyed"] },
        { zone: "gold", title: "Berth-window exposure", locator: "gold_berth_disruption*", detail: "Scheduled windows intersected with the forecast risk band. Mart not yet built.", sources: ["planned"] },
      ],
      recommendation: "Re-sequence two Panamax windows off the Thursday swell peak.",
    },
    activity: [
      { at: "2026-07-08T05:30:00Z", actor: "Sinapse", kind: "created", text: "Early-warning trigger: severe-band marine forecast intersects 6 scheduled berth windows." },
      { at: "2026-07-08T07:10:00Z", actor: "S. Mokoena", kind: "approval", text: "Accepted the recommendation — re-sequencing plan to ops for execution." },
    ],
    version: 1,
  },
  {
    id: "dec-lome-border",
    sev: "md",
    stakeholder: "Government & Policy",
    problem: "Lomé–Ouagadougou border dwell up 2.1 days",
    body: "Cinkassé border-post dwell rose 38% this quarter, eroding the corridor's cost advantage against the Tema routing.",
    valueAtRisk: { label: "Corridor trade at risk", amount: "$310M/yr" },
    confidence: 0.71,
    recommendation: "Fast-track the joint single-window pilot at Cinkassé and publish weekly dwell scorecards to both customs agencies.",
    expectedOutcome: "Return border dwell to ≤3.5 days within 90 days; protect the corridor's AfCFTA preferential volumes.",
    owner: "A. Ouédraogo · Corridor Authority",
    dueDate: "2026-08-15",
    stage: "execution",
    state: "accepted",
    relatedObjects: [
      { label: "corridor:lome-ouagadougou" },
      { label: "border:cinkasse" },
      { label: "country:tgo", href: "/ontology/country/zaf" },
      { label: "SDG 10" },
    ],
    watchers: ["Trade Ministry TGO", "Trade Ministry BFA"],
    tasks: [
      { id: "t1", title: "Sign single-window pilot MoU with both customs agencies", owner: "A. Ouédraogo", done: true },
      { id: "t2", title: "Deploy dwell-time telemetry at Cinkassé gates", owner: "Corridor PMU", done: true },
      { id: "t3", title: "Publish first weekly dwell scorecard", owner: "Sinapse · automated", done: false },
    ],
    evidence: {
      metric: "Border dwell time",
      value: "5.6 days",
      objectRef: "object · border:cinkasse",
      asOf: "quarter to 30 Jun 2026",
      confidence: 0.71,
      status: "demo",
      lineage: [
        { zone: "bronze", title: "Corridor transit logs", locator: "pillar/trade · customs*", detail: "Gate-in/gate-out events; customs feed is a deferred data product, proxied from trade telemetry.", sources: ["trade", "customs* (planned)"] },
        { zone: "silver", title: "Dwell derivation", locator: "border_dwell*", detail: "Median gate-to-gate dwell per direction, ontology-keyed to the border post.", sources: ["ontology-keyed"] },
        { zone: "gold", title: "Border Efficiency Score", locator: "gold_border_efficiency*", detail: "Dwell vs corridor benchmark. Mart not yet built.", sources: ["planned"] },
      ],
      recommendation: "Fast-track the Cinkassé single-window pilot; publish weekly dwell scorecards.",
    },
    activity: [
      { at: "2026-06-28T10:00:00Z", actor: "Sinapse", kind: "created", text: "Dwell-time anomaly crossed the corridor SLA threshold." },
      { at: "2026-06-30T08:45:00Z", actor: "A. Ouédraogo", kind: "approval", text: "Accepted — escalated to the bilateral corridor committee." },
      { at: "2026-07-02T14:20:00Z", actor: "A. Ouédraogo", kind: "task", text: "Workflow launched: 3 tasks created for the single-window pilot." },
    ],
    version: 1,
  },
  {
    id: "dec-mombasa-berth",
    sev: "gd",
    stakeholder: "DFI Investment",
    problem: "Mombasa berth-deepening tranche 2 decision due",
    body: "Tranche 1 lifted post-Panamax calls 31%. Tranche 2 ($86M) is releasable this quarter if throughput covenants hold.",
    valueAtRisk: { label: "Investment tranche", amount: "$86M" },
    confidence: 0.77,
    recommendation: "Release tranche 2 with a covenant tied to the Northern-corridor transit-time index staying under 6.5 days.",
    expectedOutcome: "+280k TEU design capacity, ≈4,100 direct/indirect jobs, SDG 9.1 corridor uplift.",
    owner: "L. Okafor · Investment Officer",
    dueDate: "2026-09-30",
    stage: "monitoring",
    state: "accepted",
    relatedObjects: [
      { label: "project:mombasa-deepening" },
      { label: "port:mombasa", href: "/ontology/port/durban" },
      { label: "SDG 9" },
      { label: "Agenda 2063 · Goal 10" },
    ],
    watchers: ["DFI Credit Committee"],
    tasks: [
      { id: "t1", title: "Verify Q2 throughput covenant from Gold marts", owner: "Sinapse · automated", done: true },
      { id: "t2", title: "Site inspection & environmental sign-off", owner: "L. Okafor", done: true },
      { id: "t3", title: "Credit committee tranche release", owner: "DFI Credit Committee", done: true },
      { id: "t4", title: "Quarterly outcome measurement vs baseline", owner: "Sinapse · automated", done: false },
    ],
    evidence: {
      metric: "Tranche-1 throughput uplift",
      value: "+31%",
      objectRef: "object · project:mombasa-deepening",
      asOf: "12 months to 30 Jun 2026",
      confidence: 0.77,
      status: "demo",
      lineage: [
        { zone: "bronze", title: "PortWatch + project PMIS", locator: "pillar/port_activity · pmis*", detail: "Daily port calls plus project milestone data (PMIS feed is a deferred data product).", sources: ["portwatch", "pmis* (planned)"] },
        { zone: "silver", title: "Baseline vs post-works", locator: "port_activity_daily", detail: "Pre/post windows around the tranche-1 completion date, ontology-keyed.", sources: ["ontology-keyed"] },
        { zone: "gold", title: "Development Impact Score", locator: "gold_dev_impact*", detail: "Throughput uplift attributed to the works. Mart not yet built.", sources: ["planned"] },
      ],
      recommendation: "Release tranche 2 with a transit-time covenant.",
    },
    activity: [
      { at: "2026-06-15T09:00:00Z", actor: "Sinapse", kind: "created", text: "Covenant check passed: tranche-1 uplift verified at +31% against baseline." },
      { at: "2026-06-20T13:30:00Z", actor: "L. Okafor", kind: "approval", text: "Accepted — tranche release moved to credit committee." },
      { at: "2026-07-01T16:00:00Z", actor: "DFI Credit Committee", kind: "action", text: "Tranche 2 released. Decision now in outcome monitoring." },
    ],
    version: 1,
  },
  {
    id: "dec-roo-datagap",
    sev: "md",
    stakeholder: "AfCFTA Monitoring",
    problem: "Rules-of-origin verification gap on 3 corridors",
    body: "Preferential-tariff claims on three West-African corridors lack digitised certificates of origin, blocking AfCFTA compliance reporting.",
    valueAtRisk: { label: "Preferential trade unverified", amount: "$1.2B/yr" },
    confidence: 0.64,
    recommendation: "Onboard the three national single-windows to the e-certificate exchange before the Q4 protocol review.",
    expectedOutcome: "Verified rules-of-origin coverage lifted from 61% to 85% of preferential claims.",
    owner: "Secretariat · Digital Trade Unit",
    dueDate: "2026-06-30",
    stage: "outcome",
    state: "accepted",
    relatedObjects: [
      { label: "afcfta:digital-trade-protocol" },
      { label: "corridor:lome-ouagadougou" },
      { label: "corridor:tema-bamako" },
      { label: "SDG 17" },
    ],
    watchers: ["AfCFTA Secretariat"],
    tasks: [
      { id: "t1", title: "Onboard TGO single-window to e-certificate exchange", owner: "Digital Trade Unit", done: true },
      { id: "t2", title: "Onboard GHA single-window to e-certificate exchange", owner: "Digital Trade Unit", done: true },
      { id: "t3", title: "Onboard NGA single-window to e-certificate exchange", owner: "Digital Trade Unit", done: true },
    ],
    evidence: {
      metric: "Verified rules-of-origin coverage",
      value: "84%",
      objectRef: "object · afcfta:digital-trade-protocol",
      asOf: "as of 30 Jun 2026",
      confidence: 0.64,
      status: "demo",
      lineage: [
        { zone: "bronze", title: "e-certificate exchange logs", locator: "pillar/trade", detail: "Certificate issuance and verification events per corridor.", sources: ["trade"] },
        { zone: "silver", title: "Claim matching", locator: "roo_verification*", detail: "Preferential claims joined to verified certificates, ontology-keyed to corridors.", sources: ["ontology-keyed"] },
        { zone: "gold", title: "Protocol compliance", locator: "gold_dtp_compliance*", detail: "Verified share of preferential trade value. Mart not yet built.", sources: ["planned"] },
      ],
      recommendation: "Sustain onboarding cadence; measured outcome 84% vs 85% target.",
    },
    activity: [
      { at: "2026-03-12T09:00:00Z", actor: "Sinapse", kind: "created", text: "Compliance gap flagged ahead of the Q4 protocol review." },
      { at: "2026-03-20T10:00:00Z", actor: "Digital Trade Unit", kind: "approval", text: "Accepted — onboarding workflow launched across three single-windows." },
      { at: "2026-07-01T08:00:00Z", actor: "Sinapse", kind: "action", text: "Outcome measured: coverage reached 84% vs 85% target — 1pt short, cadence retained." },
    ],
    version: 1,
  },
];
